### ISSUE TITLE
Entering an empty String as a Permission-Password

### ISSUE THREAD

**Issue by Haeldeus** [Mellich/JukePi#45]
When Entering "" as Password when connecting to the Server, an Error is thrown and the Client freezes.

Exception in thread "Thread-32" java.lang.ArrayIndexOutOfBoundsException: 2
    at server.connectivity.CommandHandler.standardCommand(CommandHandler.java:131)
    at server.connectivity.CommandHandler.handleCommand(CommandHandler.java:162)
    at server.connectivity.CommandHandler.run(CommandHandler.java:174)

**Comment by Mellich** [comment]
Reason of the error: an empty string is given to the addPermission Method in the network interface.
I will add a new exception in this method to prevent this error.

**Comment by Mellich** [comment]
exception added
